---
name: Push workflow for release branches

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    name: Bump and Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set repository name to variable PROJECT_SHORT_NAME
        run: |
          echo "PROJECT_SHORT_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Bump & Tag & Release
        uses: bricklanetech/github.action.bump-tag-release@v0.5.2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          slackChannelId: ${{ secrets.SLACK_CHANNEL_ID_TECHCICD }}
          slackBotToken: ${{ secrets.SLACK_TOKEN }}
